- id: "req_in_office"
  type: "location"
  loc_id: "Office"

- id: "req_in_garden"
  type: "location"
  loc_id: "Garden"

- id: "req_has_donut"
  type: "has_item"   
  item_id: "donut"

- id: "req_likes_valentino"
  type: "min_relation"
  char_id: "Valentino"
  val: 5

- id: "req_zjadl_paczka"
  type: "flag"
  flag: "valentino_zjadl_donuta"