- id: "req_in_office"
  type: "location"
  loc_id: "Office"

- id: "req_in_garden"
  type: "location"
  loc_id: "Garden"

- id: "req_has_donut"
  type: "has_item"   
  item_id: "Donut"

- id: "req_likes_valentino"
  type: "min_relation"
  char_id: "Valentino"
  value: 5

- id: "req_zjadl_paczka"
  type: "flag"
  flag: "valentino_zjadl_donuta"

- id: "req_in_anywhere"
  type: "location"
  loc_id: "any"

- id: "req_has_coin"
  type: "has_item"
  item_id: "lucky coin"

- id: "req_is_friendly_valentino"
  type: "min_relation"
  char_id: "Valentino"
  value: 10